language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - ruby-head
  - jruby-18mode
  - jruby-19mode
  - rbx-2.1.1

matrix:
  include:
    - rvm: 1.9.3
      env: RDOC_VERSION="~>3.0"
  allow_failures:
    - rvm: rbx-2.1.1
